#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
bindkey "\e[1;9C" forward-word
bindkey "\e[1;9D" backward-word
bindkey "\ez" undo

autoload -U compinit && compinit -u
  # NOTE:  `compinit -u` suppresses warnings for root shells since ~/.zprezto can be modified by UID 1000
  #        This is technically hiding a very important warning
source <(kubectl completion zsh) # this isn't ideal, but for now, it works
# source <(kind completion zsh) # this isn't ideal, but for now, it works

alias cat=batcat

true
# added by travis gem
[ -f /home/stealthybox/.travis/travis.sh ] && source /home/stealthybox/.travis/travis.sh
